# Generated by Django 5.1.1 on 2025-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='Присутній')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина відсутності')),
            ],
            options={
                'verbose_name': 'Відвідуваність',
                'verbose_name_plural': 'Відвідуваність',
                'ordering': ['lesson__date', 'student__user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Оцінка')),
                ('grade_type', models.CharField(choices=[('current', 'Поточна'), ('test', 'За тест'), ('self_study', 'За самостійну'), ('thematic', 'Тематична'), ('semester_1', 'За І семестр'), ('semester_2', 'За ІІ семестр'), ('annual', 'Річна')], default='current', max_length=20, verbose_name='Тип оцінки')),
                ('group', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Група 1'), (2, 'Група 2'), (3, 'Група 3'), (4, 'Група 4')], null=True, verbose_name='Група оцінювання')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Оцінка',
                'verbose_name_plural': 'Оцінки',
                'ordering': ['lesson__date', 'student__user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведення уроку')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-date'],
            },
        ),
    ]
