# Generated by Django 5.1.1 on 2025-05-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('journal', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student', verbose_name='Учень'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.student', verbose_name='Учень'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.lessontopic', verbose_name='Тема уроку за планом'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.schoolclass', verbose_name='Клас'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.teacher', verbose_name='Вчитель'),
        ),
        migrations.AddField(
            model_name='grade',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.lesson', verbose_name='Урок'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='journal.lesson', verbose_name='Урок'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('date', 'school_class', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'lesson', 'grade_type')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lesson')},
        ),
    ]
