# Generated by Django 5.1.1 on 2025-06-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('journal', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'lesson', 'group')},
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('current', 'Поточна'), ('test_questions', 'За тест'), ('self_study', 'За самостійну'), ('test', 'За контрольну'), ('thematic', 'Тематична'), ('semester_1', 'За І семестр'), ('semester_2', 'За ІІ семестр'), ('annual', 'Річна')], default='current', max_length=20, verbose_name='Тип оцінки'),
        ),
    ]
