# Generated by Django 5.1.1 on 2025-06-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('journal', '0003_alter_grade_unique_together_alter_grade_grade_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'lesson')},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='group',
        ),
    ]
