# Generated by Django 5.1.1 on 2025-06-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_grade_unique_together_remove_grade_group'),
        ('planning', '0004_lessonday_curriculumplan_academic_year_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='curriculum_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_grades', to='planning.curriculumunit', verbose_name='Навчальна тема (для тематичних оцінок)'),
        ),
    ]
