# Generated by Django 5.1.1 on 2025-07-01 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users_photos/', verbose_name='Фото профілю')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='По батькові')),
                ('year_of_birth', models.IntegerField(blank=True, null=True, verbose_name='Рік народження')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Додатковий опис')),
                ('admission_year', models.IntegerField(blank=True, null=True, verbose_name='Рік вступу до навчального закладу')),
                ('start_work_year', models.IntegerField(blank=True, null=True, verbose_name='Рік початку роботи')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Посада')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Досягнення')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
    ]
