# Generated by Django 5.1.1 on 2025-05-30 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_designation', models.CharField(default='A', max_length=1, verbose_name='Літерна позначка класу')),
                ('start_year', models.IntegerField(default=2010, verbose_name='Рік початку навчання (1-й клас)')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('graduated', 'Випускний'), ('closed', 'Закритий')], default='active', max_length=10, verbose_name='Статус класу')),
            ],
            options={
                'verbose_name': 'Клас',
                'verbose_name_plural': 'Класи',
                'ordering': ['start_year', 'letter_designation'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва предмету')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.schoolclass', verbose_name='Клас')),
            ],
            options={
                'verbose_name': 'Учень',
                'verbose_name_plural': 'Учні',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('children', models.ManyToManyField(related_name='parents', to='core.student', verbose_name='Діти')),
            ],
            options={
                'verbose_name': 'Батько',
                'verbose_name_plural': 'Батьки',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('classes', models.ManyToManyField(related_name='teachers', to='core.schoolclass', verbose_name='Викладає в класах')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='core.subject', verbose_name='Викладає предмети')),
            ],
            options={
                'verbose_name': 'Вчитель',
                'verbose_name_plural': 'Вчителі',
            },
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='curator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator', to='core.teacher', verbose_name='Класний керівник цього класу'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('letter_designation', 'start_year')},
        ),
    ]
