# Generated by Django 5.1.1 on 2025-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(verbose_name='Навчальний рік')),
            ],
            options={
                'verbose_name': 'Календарний план',
                'verbose_name_plural': 'Календарні плани',
            },
        ),
        migrations.CreateModel(
            name='LessonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(verbose_name='Номер уроку')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема уроку')),
                ('homework', models.TextField(blank=True, verbose_name='Домашнє завдання')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекція'), ('practice', 'Практична робота'), ('self_study', 'Самостійна робота'), ('test', 'Тестова робота'), ('control', 'Контрольна робота'), ('other', 'Інше')], default='lecture', max_length=20, verbose_name='Тип уроку')),
            ],
            options={
                'verbose_name': 'Тема уроку',
                'verbose_name_plural': 'Теми уроків',
                'ordering': ['lesson_number'],
            },
        ),
    ]
