# Generated by Django 5.1.1 on 2025-05-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumplan',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_plans', to='core.schoolclass', verbose_name='Клас'),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_plans', to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_plans', to='core.teacher', verbose_name='Вчитель'),
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_topics', to='planning.curriculumplan', verbose_name='Календарний план'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumplan',
            unique_together={('teacher', 'school_class', 'subject', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='lessontopic',
            unique_together={('plan', 'lesson_number')},
        ),
    ]
