# Generated by Django 5.1.1 on 2025-06-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontopic',
            name='group',
            field=models.IntegerField(blank=True, choices=[(None, 'Немає групи'), (1, 'Група 1'), (2, 'Група 2'), (3, 'Група 3'), (4, 'Група 4')], null=True, verbose_name='Група оцінювання'),
        ),
    ]
