# Generated by Django 5.1.1 on 2025-06-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_lessontopic_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MON', 'Понеділок'), ('TUE', 'Вівторок'), ('WED', 'Середа'), ('THU', 'Четвер'), ('FRI', "П'ятниця"), ('SAT', 'Субота'), ('SUN', 'Неділя')], max_length=3, unique=True, verbose_name='День тижня')),
            ],
            options={
                'verbose_name': 'День проведення уроку',
                'verbose_name_plural': 'Дні проведення уроків',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='academic_year_end',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець навчального року'),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='academic_year_start',
            field=models.DateField(blank=True, null=True, verbose_name='Початок навчального року'),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='semester_1_end',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець І семестру'),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='semester_1_start',
            field=models.DateField(blank=True, null=True, verbose_name='Початок І семестру'),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='semester_2_end',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець ІІ семестру'),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='semester_2_start',
            field=models.DateField(blank=True, null=True, verbose_name='Початок ІІ семестру'),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='vacation_periods_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Періоди канікул'),
        ),
        migrations.CreateModel(
            name='CurriculumUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва навчальної теми (розділу)')),
                ('order', models.IntegerField(verbose_name='Порядок теми в плані')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_units', to='planning.curriculumplan', verbose_name='Календарний план')),
            ],
            options={
                'verbose_name': 'Навчальна тема (розділ)',
                'verbose_name_plural': 'Навчальні теми (розділи)',
                'ordering': ['order'],
                'unique_together': {('plan', 'order')},
            },
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='curriculum_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_topics_in_unit', to='planning.curriculumunit', verbose_name='Навчальна тема (розділ)'),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='lesson_frequency_days',
            field=models.ManyToManyField(blank=True, to='planning.lessonday', verbose_name='Дні проведення уроків'),
        ),
    ]
